name: Bankjoy

on:
  push:
    branches:
      - main  # Runs the tests on push to the main branch
  

jobs:
  run_tests:
    runs-on: ubuntu-latest  # Use the GitHub-hosted Ubuntu runner

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure the correct Node.js version is used

      # Install dependencies (Playwright)
      - name: Install dependencies
        run: |
          npm install  # Ensure clean install of dependencies
          npm ci


      # Run Load Test with Playwright
      - name: Run test
        run: |
          npm run test 

      # Generate the Allure report
      - name: Generate Allure Report
        run: |
          npm run report  

      # Upload the report as an artifact for later viewing
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./playwright-report/*.html
            ./playwright-report/allure-report/*.html
          retention-days: 30

          
      # Upload the HTML as an artifact for later viewing
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: avg-results
          path: |
            ./report/*.html
          retention-days: 30
